using System;
using System.Collections.Generic;
using System.Linq;

namespace UnityEngine.Rendering.Universal
{
    public enum UniversalLightType
    {
        /// <summary>Spot Light. Complete this type by setting the SpotLightShape too.</summary>
        Spot = LightType.Spot,
        /// <summary>Directional Light.</summary>
        Directional = LightType.Directional,
        /// <summary>Point Light.</summary>
        Point = LightType.Point,
    }
    
    /// <summary>
    /// Unit of the lights supported in HDRP
    /// </summary>
    public enum LightUnit
    {
        /// <summary>Total power/flux emitted by the light.</summary>
        Lumen,
        /// <summary>Flux per steradian.</summary>
        Candela,    // lm/sr
        /// <summary>Flux per unit area.</summary>
        Lux,        // lm/m²
        /// <summary>Flux per unit area and per steradian.</summary>
        Nits,       // lm/m²/sr
        /// <summary>ISO 100 Exposure Value (https://en.wikipedia.org/wiki/Exposure_value).</summary>
        Ev100,
    }
    
    internal enum DirectionalLightUnit
    {
        Lux = LightUnit.Lux,
    }
    
    internal enum AreaLightUnit
    {
        Lumen = LightUnit.Lumen,
        Nits = LightUnit.Nits,
        Ev100 = LightUnit.Ev100,
    }

    internal enum PunctualLightUnit
    {
        Lumen = LightUnit.Lumen,
        Candela = LightUnit.Candela,
        Lux = LightUnit.Lux,
        Ev100 = LightUnit.Ev100
    }
    
    public partial class UniversalAdditionalLightData
    {
        [System.NonSerialized]
        static Dictionary<int, LightUnit[]> supportedLightTypeCache = new Dictionary<int, LightUnit[]>();
        
        //Not to be used in render loop instead as we can add on the fly an
        //HDAdditionalLightData that is not really added to the GameObject
        //In this case, use ComputeLightType directly.
        //This is for scripting and case where the HDAdditionnalLightData is existing
        /// <summary>
        /// The type of light used.
        /// This handle some internal conversion in Light component for culling purpose.
        /// </summary>
        public UniversalLightType type
        {
            get => ComputeLightType(light);
            set
            {
                if (type != value)
                {
                    switch (value)
                    {
                        case UniversalLightType.Directional:
                            light.type = LightType.Directional;
                            break;
                        case UniversalLightType.Point:
                            light.type = LightType.Point;
                            break;
                        case UniversalLightType.Spot:
                            light.type = LightType.Spot;
                            break;
                        default:
                            Debug.Assert(false, $"Unknown {typeof(UniversalLightType).Name} {value}.");
                            break;
                    }
                    
                    // If the current light unit is not supported by the new light type, we change it
                    var supportedUnits = GetSupportedLightUnits(value);
                    if (!supportedUnits.Any(u => u == lightUnit))
                        lightUnit = supportedUnits.First();
                    
                    UpdateAllLightValues();
                }
            }
        }
        
        string GetLightTypeName()
        {
            return $"{light.type}Light";
        }
        
        /// <summary>
        /// Give the supported lights unit for the given parameters
        /// </summary>
        /// <param name="type">The type of the light</param>
        /// <param name="spotLightShape">the shape of the spot.You can put anything in case it is not a spot light.</param>
        /// <returns>Array of supported units</returns>
        public static LightUnit[] GetSupportedLightUnits(UniversalLightType type)
        {
            LightUnit[] supportedTypes;

            // Combine the two light types to access the dictionary
            int cacheKey = ((int)type & 0xFF) << 0;

            // We cache the result once they are computed, it avoid garbage generated by Enum.GetValues and Linq.
            if (supportedLightTypeCache.TryGetValue(cacheKey, out supportedTypes))
                return supportedTypes;
            
            if (type == UniversalLightType.Directional)
                supportedTypes = Enum.GetValues(typeof(DirectionalLightUnit)).Cast<LightUnit>().ToArray();
            else
                supportedTypes = Enum.GetValues(typeof(PunctualLightUnit)).Cast<LightUnit>().ToArray();

            supportedLightTypeCache[cacheKey] = supportedTypes;

            return supportedTypes;
        }
        
        /// <summary>
        /// Check if the given type is supported by this type and shape.
        /// </summary>
        /// <param name="type">The type of the light</param>
        /// <param name="spotLightShape">the shape of the spot.You can put anything in case it is not a spot light.</param>
        /// <param name="unit">The unit to check</param>
        /// <returns>True: this unit is supported</returns>
        public static bool IsValidLightUnitForType(UniversalLightType type, LightUnit unit)
        {
            LightUnit[] allowedUnits = GetSupportedLightUnits(type);

            return allowedUnits.Any(u => u == unit);
        }
        
        internal static UniversalLightType TranslateLightType(LightType lightType)
        {
            switch (lightType)
            {
                case LightType.Spot: return UniversalLightType.Spot;
                case LightType.Directional: return UniversalLightType.Directional;
                case LightType.Point: return UniversalLightType.Point;
                default: return UniversalLightType.Point;
            }
        }
        
        //To use in render loop instead of type as we can add on the fly an
        //HDAdditionalLightData that is not really added to the GameObject
        //In this case, the type property will return a false value as this will
        //be base on a default(HDAdditionnalData) which will have a point type
        internal UniversalLightType ComputeLightType(Light attachedLight)
        {
            // Shuriken lights won't have a Light component.
            if (attachedLight == null)
                return UniversalLightType.Point;

            UniversalLightType universalLightType = TranslateLightType(attachedLight.type);

            return universalLightType;
        }
    }
}